### ISSUE TITLE
Show admin notice when no product IDs entered

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-allowed-products#1]
Too many people install the add-on and don't configure it. When no products are entered, nothing is allowed, therefore all products will be blocked from earning a commission.

I propose we show an admin notice when no product IDs have been entered so the user at least knows they need to enter something, or remove the add-on.

**Comment by michaelbeil** [comment]
10000%

**Comment by wordmaid** [comment]
:+1: this would be everything.

**Comment by sumobi** [comment]
done
