### ISSUE TITLE
i:WooCommerce - Allowing referrals on all products with WooCommerce

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-allowed-products#14]
Using the latest version of Allowed Products:  1.1.1
Testing on sandbox site: http://s14890.p27.sites.pressdns.com/woo

* Have two products enabled under _Affiliates > Integrations_ 
![allow-product-ids](https://user-images.githubusercontent.com/3018245/31144914-fb8621a8-a836-11e7-8179-a39cd1069c43.png)

Used affiliate link to purchase product with id of 56 and it created a referral.

**Comment by gspice** [comment]
Testing using Easy Digital Downloads - it correctly blocked referrals on products that were not named under _Affiliates > Integrations_ except for one, it created a zero amount referral.

**Comment by pippinsplugins** [comment]
@gspice I saw a comment yesterday regarding the zero dollar referral option.

Did disabling $0 referrals solve the problem?

**Comment by gspice** [comment]
@pippinsplugins It solved it for edd but not woo, just tried again on sandbox - gave me the full referral for a product id (19) that is not on the "allowed" list.

**Comment by pippinsplugins** [comment]
@gspice does your product use variations?

**Comment by gspice** [comment]
@pippinsplugins I tested with again with two products, one is simple pricing and one is variable product, both created referrals.

**Comment by amdrew** [comment]
Couldn't replicate this locally, it corrected generated a $0 referral for a product that wasn't listed, and with ignore $0 referrals enabled, it didn't show up at all. Going to have a look at the sandbox site.

**Comment by amdrew** [comment]
Yeah, definitely an issue on the sandbox site, though same plugin versions and everything as my local set up. Tried without the other plugins active, same result. Also tried matching settings from WooCommerce/AffiliateWP with my local installation. No luck so far.

**Comment by ramiabraham** [comment]
Same here - no luck locally, confirmed the issue on the sandbox site though. Going to try replicating on local multisite.

**Comment by ramiabraham** [comment]
I set up a new WC sub-site on sandbox, and the issue does not occur there:

http://s14890.p27.sites.pressdns.com/woo2

Like testing locally, a $0 referral was generated prior to disabling the zero referrals setting. When disabling zero referrals, no referral is generated for products which are not allowed.

**Comment by amdrew** [comment]
@ramiabraham If I remember correctly, generating a $0 commission is expected behavior, until the ignore $0 referrals is enabled. Since the add-on was originally built we have added a new filter to AffiliateWP that can block the entire referral. I think we felt that at least logging a $0 referral was a good indication and so haven't changed it since.

**Comment by amdrew** [comment]
@gspice Forgive me if I missed something but did a customer report this issue originally, or is it something you just happened to find on the sandbox site?

**Comment by gspice** [comment]
@amdrew Yes!  This was from a support ticket....sorry, forgot to post the link.  I finally found it:
https://secure.helpscout.net/conversation/442830363/67825/?folderId=205529

**Comment by gspice** [comment]
This one is outdated, meaning, we came across a similar bug in #17 and it was fixed.
