### ISSUE TITLE
Allowing referrals for all products on Woo and EDD integrations

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-allowed-products#17]
@tubiz 

First reported on HS ticket:
https://secure.helpscout.net/conversation/653232749/89044?folderId=1170842

Reported as possible Lifetime Commissions bug....subsequent purchase from a customer already attached to an affiliate via LC created a referral on products that were not specified in the Allowed Products list under _Affiliates > Integrations_.

However, after further testing it appears to be creating referrals for all products regardless of what is specified.  

**To reproduce:**

* Install and activate Allowed Products with either a WooCommerce or Easy Digital Downloads integration.
* Do not populate any product ids like this for ease of testing:
<img width="860" alt="allowed-products" src="https://user-images.githubusercontent.com/3018245/44885948-97f0e500-ac78-11e8-84ee-7f0b2bd88f16.png">
* With the above settings, only zero-amount referrals should be created, however, in my testing they all had dollar amounts based on the referral rates set with Woo or EDD.

**Comment by tubiz** [comment]
PR: #18

@gspice the issue has been fixed in this PR. 

You have to use this AffiliateWP branch to test https://github.com/AffiliateWP/AffiliateWP/tree/issue/2794

**Comment by pippinsplugins** [comment]
I'm going to go ahead and push this release out ahead of the core update.
