### ISSUE TITLE
Referrals generated for 0.00

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-allowed-products#22]
While testing on WordPress 5.2, I noticed that a referral is generated for 0.00. This happens on WordPress 5.1.1 as well. This appears to be connected to https://github.com/AffiliateWP/affiliatewp-allowed-products/issues/12.

**Comment by DrewAPicture** [comment]
We'll look into it, thanks @michaelbeil. Question: Did you have any other add-ons active at the time you tested this?

@alexstandiford Can you please take a look here, probably need to test as far back as 5.0 just to make sure we're covered.

**Comment by michaelbeil** [comment]
@DrewAPicture I did not. I only had AffiliateWP and Allowed Products active when I tested.

**Comment by amdrew** [comment]
I tested with 5.1.1 and a referral was generating at the correct amount. @michaelbeil Did you make a test purchase of the product that you added to the Allowed Products input field? If you purchased a product not listed there it would be generated as a $0.00 referral.

**Comment by michaelbeil** [comment]
@amdrew I purchased a product _not_ listed in the Allowed Products input field. I thought _no_ referral would be generated, but if a 0.00 referral is expected, then everything is working correctly.
