### ISSUE TITLE
product with special commission percentage

### ISSUE THREAD

**Issue by ershadzolfi** [AffiliateWP/affiliatewp-allowed-products#32]
Hi,
It would be good if we could set products with percentage.
By now you have affiliate product rate per user, but we can not change product rate for every user, we need global product rate for all user.

[Edited for civility]

**Comment by DrewAPicture** [comment]
We already support global product rates for most of our official integrations. To treat product rates as percentages, you will need to configure the [referral rate type](https://docs.affiliatewp.com/article/1772-general-settings) setting in Affiliates → Settings.

You can read more about specific integrations' features here: https://docs.affiliatewp.com/category/75-integrations
