### ISSUE TITLE
All commission rates set to 0 when used with a non-supported integration

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-allowed-products#6]
_[noted via slack by @pippinsplugins 17:59:00 UTC]_

`Allowed Products` add-on will cause all commission rates to be set to 0 when it's used with a non supported integration

For example, a site uses _Paid Memberships Pro_ and _WooCommerce_. `Allowed Products` does not support Paid Memberships Pro, but will cause all referrals in PMP to be set to 0.00

**Comment by DrewAPicture** [comment]
Added a PR: #9 

The PR takes a slightly different tack, by zeroing out the rate for products that are both not in the array and of a supported integration (EDD, WooCommerce, MemberMouse).

**Comment by pippinsplugins** [comment]
@sumobi could you test this please?

**Comment by sumobi** [comment]
@DrewAPicture Left one comment about the notice, otherwise works well 👍
